[package]
name = "v65"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
crossterm = "0.27.0"
log = "0.4.20"
log_buffer = "1.2.0"
simplelog = "0.12.1"
